package com.example.bazaar.Model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

data class UserPost (
    // Auth information
    var userName: String = "",
    var title: String = "",
    var description: String = "",
    var price: Int = 0,
    var ownerUid: String = "",
    var pictureUUIDs: List<String> = listOf(),
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)