package com.example.bazaar.Model

import com.example.bazaar.ui.createPost.Category
import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

data class UserPost (
    // Auth information
    var userName: String = "",
    var userEmail: String = "",
    var title: String = "",
    var description: String = "",
    var phoneNumber: String = "",
    var price: Int = 0,
    var city: String = "",
    var state: String = "",
    var countryCode: String= "",
    var category: String = "",
    var ownerUid: String = "",
    var pictureUUIDs: List<String> = listOf(),
    var aptInfo: AptInfo? = null,
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)

class AptInfo (
    var squareFeet: Int = 0,
    var rooms:  Int = 0,
    var baths: Int = 0,
)